### ISSUE TITLE
unexpected panic on attempt to parse "d0</**/"

### ISSUE THREAD

**Issue by dwrensha** [dtolnay/syn#340]
```toml
# Cargo.toml

[package]
name = "test-syn"
version = "0.1.0"

[dependencies.syn]
git = "https://github.com/dtolnay/syn"
features = ["parsing", "full"]
```

```rust
// src/main.rs

extern crate syn;

fn main() {
    let _ = syn::parse_file("d0</**/");
}
```

```
$ rustc --version -v
rustc 1.23.0 (766bd11c8 2018-01-01)
binary: rustc
commit-hash: 766bd11c8a3c019ca53febdcd77b2215379dd67d
commit-date: 2018-01-01
host: x86_64-unknown-linux-gnu
release: 1.23.0
LLVM version: 4.0
$ RUST_BACKTRACE=1 cargo run         
   Compiling syn v0.12.7 (https://github.com/dtolnay/syn#139efc6f)
   Compiling test-syn v0.1.0 (file:///home/dwrensha/Desktop/test-syn)
    Finished dev [unoptimized + debuginfo] target(s) in 8.44 secs
     Running `target/debug/test-syn`
thread 'main' panicked at 'Unrecognized literal: /**/', /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/lit.rs:550:12
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: syn::lit::value::<impl syn::lit::Lit>::new
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/lit.rs:550
   8: syn::lit::parsing::<impl syn::synom::Synom for syn::lit::Lit>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/lit.rs:334
   9: syn::expr::parsing::<impl syn::synom::Synom for syn::expr::ExprLit>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/parsers.rs:69
  10: syn::path::parsing::<impl syn::synom::Synom for syn::path::GenericArgument>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/parsers.rs:69
  11: <syn::punctuated::Punctuated<T, P>>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/punctuated.rs:600
  12: <syn::punctuated::Punctuated<T, P>>::parse_terminated_with
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/punctuated.rs:577
  13: <syn::punctuated::Punctuated<T, P>>::parse_terminated
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/punctuated.rs:535
  14: syn::path::parsing::<impl syn::synom::Synom for syn::path::AngleBracketedGenericArguments>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/parsers.rs:69
  15: syn::path::parsing::<impl syn::synom::Synom for syn::path::PathSegment>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/parsers.rs:69
  16: <syn::punctuated::Punctuated<T, P>>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/punctuated.rs:600
  17: <syn::punctuated::Punctuated<T, P>>::parse_separated_nonempty_with
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/punctuated.rs:565
  18: <syn::punctuated::Punctuated<T, P>>::parse_separated_nonempty
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/punctuated.rs:529
  19: syn::path::parsing::<impl syn::synom::Synom for syn::path::Path>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/parsers.rs:69
  20: syn::item::parsing::<impl syn::synom::Synom for syn::item::ItemMacro>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/parsers.rs:69
  21: syn::item::parsing::<impl syn::synom::Synom for syn::item::Item>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/parsers.rs:69
  22: syn::parsers::many0
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/parsers.rs:504
  23: syn::file::parsing::<impl syn::synom::Synom for syn::file::File>::parse
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/parsers.rs:69
  24: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  25: <F as syn::synom::Parser>::parse2
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/synom.rs:222
  26: syn::parse2
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/lib.rs:601
  27: syn::parse_str
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/lib.rs:640
  28: syn::parse_file
             at /home/dwrensha/.cargo/git/checkouts/syn-6f4912dca572d3ab/139efc6/src/lib.rs:704
  29: test_syn::main
             at src/main.rs:6
  30: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  31: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  32: main
  33: __libc_start_main
  34: _start
```

Found via [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz).

**Comment by dwrensha** [comment]
Weirdly, `proc-macro2` seems to consider comments to be literals: https://github.com/alexcrichton/proc-macro2/blob/8c03033828a614775017f078a01f2c457957975b/src/stable.rs#L721

**Comment by dtolnay** [comment]
Thanks! I believe this is a proc-macro2 bug. I filed https://github.com/alexcrichton/proc-macro2/issues/57 to follow up.
