### ISSUE TITLE
Cannot access a scoped thread local variable without calling `set` first

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/syn#375]
Every libsyntax-using test we have is currently failing in CI with the following stack trace.

```
FAIL - libsyntax failed to parse raw
thread '<unnamed>' panicked at 'cannot access a scoped thread local variable without calling `set` first', /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:186:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic
   6: <scoped_tls::ScopedKey<T>>::with
   7: syntax_pos::symbol::Ident::from_str
   8: syntax::parse::lexer::StringReader::next_token_inner
   9: syntax::parse::lexer::StringReader::advance_token
  10: syntax::parse::lexer::StringReader::new
  11: syntax::parse::filemap_to_stream
  12: syntax::parse::filemap_to_parser
  13: syntax::parse::parse_expr_from_source_str
  14: std::panicking::try::do_call
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  16: test_precedence::common::parse::libsyntax_expr
  17: test_precedence::test_expressions
  18: rayon::iter::plumbing::Producer::fold_with
  19: rayon::iter::plumbing::bridge_producer_consumer::helper
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  22: rayon_core::registry::in_worker
  23: rayon::iter::plumbing::bridge_producer_consumer::helper
  24: std::panicking::try::do_call
  25: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  26: rayon_core::registry::in_worker
  27: rayon::iter::plumbing::bridge_producer_consumer::helper
  28: std::panicking::try::do_call
  29: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  31: std::panicking::try::do_call
  32: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  33: <rayon_core::job::StackJob<L, F, R> as rayon_core::job::Job>::execute
  34: rayon_core::registry::WorkerThread::wait_until_cold
  35: rayon_core::registry::main_loop
  36: std::panicking::try::do_call
  37: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  38: <F as alloc::boxed::FnBox<A>>::call_box
  39: std::sys_common::thread::start_thread
             at /checkout/src/liballoc/boxed.rs:793
             at libstd/sys_common/thread.rs:24
  40: std::sys::unix::thread::Thread::new::thread_start
             at libstd/sys/unix/thread.rs:90
  41: start_thread
  42: clone
libsyntax panicked
```

**Comment by dtolnay** [comment]
Fixed in 5d1a3ee883591e576165092f91ead5001e76d50f.
